        .section .rodata
        .type iris_data, @object
        .globl iris_data
iris_data:
        .ascii "1\0\0\0"
        .float 5.1, 3.5, 1.4, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "2\0\0\0"
        .float 4.9, 3, 1.4, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "3\0\0\0"
        .float 4.7, 3.2, 1.3, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "4\0\0\0"
        .float 4.6, 3.1, 1.5, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "5\0\0\0"
        .float 5, 3.6, 1.4, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "6\0\0\0"
        .float 5.4, 3.9, 1.7, 0.4
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "7\0\0\0"
        .float 4.6, 3.4, 1.4, 0.3
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "8\0\0\0"
        .float 5, 3.4, 1.5, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "9\0\0\0"
        .float 4.4, 2.9, 1.4, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "10\0\0"
        .float 4.9, 3.1, 1.5, 0.1
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "11\0\0"
        .float 5.4, 3.7, 1.5, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "12\0\0"
        .float 4.8, 3.4, 1.6, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "13\0\0"
        .float 4.8, 3, 1.4, 0.1
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "14\0\0"
        .float 4.3, 3, 1.1, 0.1
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "15\0\0"
        .float 5.8, 4, 1.2, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "16\0\0"
        .float 5.7, 4.4, 1.5, 0.4
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "17\0\0"
        .float 5.4, 3.9, 1.3, 0.4
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "18\0\0"
        .float 5.1, 3.5, 1.4, 0.3
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "19\0\0"
        .float 5.7, 3.8, 1.7, 0.3
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "20\0\0"
        .float 5.1, 3.8, 1.5, 0.3
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "21\0\0"
        .float 5.4, 3.4, 1.7, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "22\0\0"
        .float 5.1, 3.7, 1.5, 0.4
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "23\0\0"
        .float 4.6, 3.6, 1, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "24\0\0"
        .float 5.1, 3.3, 1.7, 0.5
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "25\0\0"
        .float 4.8, 3.4, 1.9, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "26\0\0"
        .float 5, 3, 1.6, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "27\0\0"
        .float 5, 3.4, 1.6, 0.4
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "28\0\0"
        .float 5.2, 3.5, 1.5, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "29\0\0"
        .float 5.2, 3.4, 1.4, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "30\0\0"
        .float 4.7, 3.2, 1.6, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "31\0\0"
        .float 4.8, 3.1, 1.6, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "32\0\0"
        .float 5.4, 3.4, 1.5, 0.4
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "33\0\0"
        .float 5.2, 4.1, 1.5, 0.1
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "34\0\0"
        .float 5.5, 4.2, 1.4, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "35\0\0"
        .float 4.9, 3.1, 1.5, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "36\0\0"
        .float 5, 3.2, 1.2, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "37\0\0"
        .float 5.5, 3.5, 1.3, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "38\0\0"
        .float 4.9, 3.6, 1.4, 0.1
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "39\0\0"
        .float 4.4, 3, 1.3, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "40\0\0"
        .float 5.1, 3.4, 1.5, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "41\0\0"
        .float 5, 3.5, 1.3, 0.3
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "42\0\0"
        .float 4.5, 2.3, 1.3, 0.3
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "43\0\0"
        .float 4.4, 3.2, 1.3, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "44\0\0"
        .float 5, 3.5, 1.6, 0.6
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "45\0\0"
        .float 5.1, 3.8, 1.9, 0.4
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "46\0\0"
        .float 4.8, 3, 1.4, 0.3
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "47\0\0"
        .float 5.1, 3.8, 1.6, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "48\0\0"
        .float 4.6, 3.2, 1.4, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "49\0\0"
        .float 5.3, 3.7, 1.5, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "50\0\0"
        .float 5, 3.3, 1.4, 0.2
        .ascii "setosa\0\0\0\0\0\0"
        .ascii "51\0\0"
        .float 7, 3.2, 4.7, 1.4
        .ascii "versicolor\0\0"
        .ascii "52\0\0"
        .float 6.4, 3.2, 4.5, 1.5
        .ascii "versicolor\0\0"
        .ascii "53\0\0"
        .float 6.9, 3.1, 4.9, 1.5
        .ascii "versicolor\0\0"
        .ascii "54\0\0"
        .float 5.5, 2.3, 4, 1.3
        .ascii "versicolor\0\0"
        .ascii "55\0\0"
        .float 6.5, 2.8, 4.6, 1.5
        .ascii "versicolor\0\0"
        .ascii "56\0\0"
        .float 5.7, 2.8, 4.5, 1.3
        .ascii "versicolor\0\0"
        .ascii "57\0\0"
        .float 6.3, 3.3, 4.7, 1.6
        .ascii "versicolor\0\0"
        .ascii "58\0\0"
        .float 4.9, 2.4, 3.3, 1
        .ascii "versicolor\0\0"
        .ascii "59\0\0"
        .float 6.6, 2.9, 4.6, 1.3
        .ascii "versicolor\0\0"
        .ascii "60\0\0"
        .float 5.2, 2.7, 3.9, 1.4
        .ascii "versicolor\0\0"
        .ascii "61\0\0"
        .float 5, 2, 3.5, 1
        .ascii "versicolor\0\0"
        .ascii "62\0\0"
        .float 5.9, 3, 4.2, 1.5
        .ascii "versicolor\0\0"
        .ascii "63\0\0"
        .float 6, 2.2, 4, 1
        .ascii "versicolor\0\0"
        .ascii "64\0\0"
        .float 6.1, 2.9, 4.7, 1.4
        .ascii "versicolor\0\0"
        .ascii "65\0\0"
        .float 5.6, 2.9, 3.6, 1.3
        .ascii "versicolor\0\0"
        .ascii "66\0\0"
        .float 6.7, 3.1, 4.4, 1.4
        .ascii "versicolor\0\0"
        .ascii "67\0\0"
        .float 5.6, 3, 4.5, 1.5
        .ascii "versicolor\0\0"
        .ascii "68\0\0"
        .float 5.8, 2.7, 4.1, 1
        .ascii "versicolor\0\0"
        .ascii "69\0\0"
        .float 6.2, 2.2, 4.5, 1.5
        .ascii "versicolor\0\0"
        .ascii "70\0\0"
        .float 5.6, 2.5, 3.9, 1.1
        .ascii "versicolor\0\0"
        .ascii "71\0\0"
        .float 5.9, 3.2, 4.8, 1.8
        .ascii "versicolor\0\0"
        .ascii "72\0\0"
        .float 6.1, 2.8, 4, 1.3
        .ascii "versicolor\0\0"
        .ascii "73\0\0"
        .float 6.3, 2.5, 4.9, 1.5
        .ascii "versicolor\0\0"
        .ascii "74\0\0"
        .float 6.1, 2.8, 4.7, 1.2
        .ascii "versicolor\0\0"
        .ascii "75\0\0"
        .float 6.4, 2.9, 4.3, 1.3
        .ascii "versicolor\0\0"
        .ascii "76\0\0"
        .float 6.6, 3, 4.4, 1.4
        .ascii "versicolor\0\0"
        .ascii "77\0\0"
        .float 6.8, 2.8, 4.8, 1.4
        .ascii "versicolor\0\0"
        .ascii "78\0\0"
        .float 6.7, 3, 5, 1.7
        .ascii "versicolor\0\0"
        .ascii "79\0\0"
        .float 6, 2.9, 4.5, 1.5
        .ascii "versicolor\0\0"
        .ascii "80\0\0"
        .float 5.7, 2.6, 3.5, 1
        .ascii "versicolor\0\0"
        .ascii "81\0\0"
        .float 5.5, 2.4, 3.8, 1.1
        .ascii "versicolor\0\0"
        .ascii "82\0\0"
        .float 5.5, 2.4, 3.7, 1
        .ascii "versicolor\0\0"
        .ascii "83\0\0"
        .float 5.8, 2.7, 3.9, 1.2
        .ascii "versicolor\0\0"
        .ascii "84\0\0"
        .float 6, 2.7, 5.1, 1.6
        .ascii "versicolor\0\0"
        .ascii "85\0\0"
        .float 5.4, 3, 4.5, 1.5
        .ascii "versicolor\0\0"
        .ascii "86\0\0"
        .float 6, 3.4, 4.5, 1.6
        .ascii "versicolor\0\0"
        .ascii "87\0\0"
        .float 6.7, 3.1, 4.7, 1.5
        .ascii "versicolor\0\0"
        .ascii "88\0\0"
        .float 6.3, 2.3, 4.4, 1.3
        .ascii "versicolor\0\0"
        .ascii "89\0\0"
        .float 5.6, 3, 4.1, 1.3
        .ascii "versicolor\0\0"
        .ascii "90\0\0"
        .float 5.5, 2.5, 4, 1.3
        .ascii "versicolor\0\0"
        .ascii "91\0\0"
        .float 5.5, 2.6, 4.4, 1.2
        .ascii "versicolor\0\0"
        .ascii "92\0\0"
        .float 6.1, 3, 4.6, 1.4
        .ascii "versicolor\0\0"
        .ascii "93\0\0"
        .float 5.8, 2.6, 4, 1.2
        .ascii "versicolor\0\0"
        .ascii "94\0\0"
        .float 5, 2.3, 3.3, 1
        .ascii "versicolor\0\0"
        .ascii "95\0\0"
        .float 5.6, 2.7, 4.2, 1.3
        .ascii "versicolor\0\0"
        .ascii "96\0\0"
        .float 5.7, 3, 4.2, 1.2
        .ascii "versicolor\0\0"
        .ascii "97\0\0"
        .float 5.7, 2.9, 4.2, 1.3
        .ascii "versicolor\0\0"
        .ascii "98\0\0"
        .float 6.2, 2.9, 4.3, 1.3
        .ascii "versicolor\0\0"
        .ascii "99\0\0"
        .float 5.1, 2.5, 3, 1.1
        .ascii "versicolor\0\0"
        .ascii "100\0"
        .float 5.7, 2.8, 4.1, 1.3
        .ascii "versicolor\0\0"
        .ascii "101\0"
        .float 6.3, 3.3, 6, 2.5
        .ascii "virginica\0\0\0"
        .ascii "102\0"
        .float 5.8, 2.7, 5.1, 1.9
        .ascii "virginica\0\0\0"
        .ascii "103\0"
        .float 7.1, 3, 5.9, 2.1
        .ascii "virginica\0\0\0"
        .ascii "104\0"
        .float 6.3, 2.9, 5.6, 1.8
        .ascii "virginica\0\0\0"
        .ascii "105\0"
        .float 6.5, 3, 5.8, 2.2
        .ascii "virginica\0\0\0"
        .ascii "106\0"
        .float 7.6, 3, 6.6, 2.1
        .ascii "virginica\0\0\0"
        .ascii "107\0"
        .float 4.9, 2.5, 4.5, 1.7
        .ascii "virginica\0\0\0"
        .ascii "108\0"
        .float 7.3, 2.9, 6.3, 1.8
        .ascii "virginica\0\0\0"
        .ascii "109\0"
        .float 6.7, 2.5, 5.8, 1.8
        .ascii "virginica\0\0\0"
        .ascii "110\0"
        .float 7.2, 3.6, 6.1, 2.5
        .ascii "virginica\0\0\0"
        .ascii "111\0"
        .float 6.5, 3.2, 5.1, 2
        .ascii "virginica\0\0\0"
        .ascii "112\0"
        .float 6.4, 2.7, 5.3, 1.9
        .ascii "virginica\0\0\0"
        .ascii "113\0"
        .float 6.8, 3, 5.5, 2.1
        .ascii "virginica\0\0\0"
        .ascii "114\0"
        .float 5.7, 2.5, 5, 2
        .ascii "virginica\0\0\0"
        .ascii "115\0"
        .float 5.8, 2.8, 5.1, 2.4
        .ascii "virginica\0\0\0"
        .ascii "116\0"
        .float 6.4, 3.2, 5.3, 2.3
        .ascii "virginica\0\0\0"
        .ascii "117\0"
        .float 6.5, 3, 5.5, 1.8
        .ascii "virginica\0\0\0"
        .ascii "118\0"
        .float 7.7, 3.8, 6.7, 2.2
        .ascii "virginica\0\0\0"
        .ascii "119\0"
        .float 7.7, 2.6, 6.9, 2.3
        .ascii "virginica\0\0\0"
        .ascii "120\0"
        .float 6, 2.2, 5, 1.5
        .ascii "virginica\0\0\0"
        .ascii "121\0"
        .float 6.9, 3.2, 5.7, 2.3
        .ascii "virginica\0\0\0"
        .ascii "122\0"
        .float 5.6, 2.8, 4.9, 2
        .ascii "virginica\0\0\0"
        .ascii "123\0"
        .float 7.7, 2.8, 6.7, 2
        .ascii "virginica\0\0\0"
        .ascii "124\0"
        .float 6.3, 2.7, 4.9, 1.8
        .ascii "virginica\0\0\0"
        .ascii "125\0"
        .float 6.7, 3.3, 5.7, 2.1
        .ascii "virginica\0\0\0"
        .ascii "126\0"
        .float 7.2, 3.2, 6, 1.8
        .ascii "virginica\0\0\0"
        .ascii "127\0"
        .float 6.2, 2.8, 4.8, 1.8
        .ascii "virginica\0\0\0"
        .ascii "128\0"
        .float 6.1, 3, 4.9, 1.8
        .ascii "virginica\0\0\0"
        .ascii "129\0"
        .float 6.4, 2.8, 5.6, 2.1
        .ascii "virginica\0\0\0"
        .ascii "130\0"
        .float 7.2, 3, 5.8, 1.6
        .ascii "virginica\0\0\0"
        .ascii "131\0"
        .float 7.4, 2.8, 6.1, 1.9
        .ascii "virginica\0\0\0"
        .ascii "132\0"
        .float 7.9, 3.8, 6.4, 2
        .ascii "virginica\0\0\0"
        .ascii "133\0"
        .float 6.4, 2.8, 5.6, 2.2
        .ascii "virginica\0\0\0"
        .ascii "134\0"
        .float 6.3, 2.8, 5.1, 1.5
        .ascii "virginica\0\0\0"
        .ascii "135\0"
        .float 6.1, 2.6, 5.6, 1.4
        .ascii "virginica\0\0\0"
        .ascii "136\0"
        .float 7.7, 3, 6.1, 2.3
        .ascii "virginica\0\0\0"
        .ascii "137\0"
        .float 6.3, 3.4, 5.6, 2.4
        .ascii "virginica\0\0\0"
        .ascii "138\0"
        .float 6.4, 3.1, 5.5, 1.8
        .ascii "virginica\0\0\0"
        .ascii "139\0"
        .float 6, 3, 4.8, 1.8
        .ascii "virginica\0\0\0"
        .ascii "140\0"
        .float 6.9, 3.1, 5.4, 2.1
        .ascii "virginica\0\0\0"
        .ascii "141\0"
        .float 6.7, 3.1, 5.6, 2.4
        .ascii "virginica\0\0\0"
        .ascii "142\0"
        .float 6.9, 3.1, 5.1, 2.3
        .ascii "virginica\0\0\0"
        .ascii "143\0"
        .float 5.8, 2.7, 5.1, 1.9
        .ascii "virginica\0\0\0"
        .ascii "144\0"
        .float 6.8, 3.2, 5.9, 2.3
        .ascii "virginica\0\0\0"
        .ascii "145\0"
        .float 6.7, 3.3, 5.7, 2.5
        .ascii "virginica\0\0\0"
        .ascii "146\0"
        .float 6.7, 3, 5.2, 2.3
        .ascii "virginica\0\0\0"
        .ascii "147\0"
        .float 6.3, 2.5, 5, 1.9
        .ascii "virginica\0\0\0"
        .ascii "148\0"
        .float 6.5, 3, 5.2, 2
        .ascii "virginica\0\0\0"
        .ascii "149\0"
        .float 6.2, 3.4, 5.4, 2.3
        .ascii "virginica\0\0\0"
        .ascii "150\0"
        .float 5.9, 3, 5.1, 1.8
        .ascii "virginica\0\0\0"
        .size iris_data, .-iris_data
	.section .note.GNU-stack,"",@progbits
